######################################################################
# Automatically generated by qmake (3.0) Mon Jan 9 09:22:10 2017
######################################################################

QT += gui widgets
TEMPLATE = app
TARGET = 01-set-geometry
INCLUDEPATH += .

# Input
SOURCES += main.cpp
