######################################################################
# Automatically generated by qmake (3.0) Mon Jan 9 10:15:00 2017
######################################################################

QT += core gui widgets

TEMPLATE = app
TARGET = 03-grid
INCLUDEPATH += .

# Input
SOURCES += main.cpp
