######################################################################
# Automatically generated by qmake (3.0) Mon Jan 9 21:05:13 2017
######################################################################

QT += widgets
TEMPLATE = app
TARGET = 01-palettes
INCLUDEPATH += .

# Input
SOURCES += main.cpp
